name: Run Tests

on:
  workflow_dispatch:  # Manual trigger via GitHub UI button

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.*']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version == '3.*' && '>=3.13' || matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda info
          conda list
          pip install -e ".[dev]"

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest tests/ -v --cov=autoCLI_config --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
